remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

title: Habib hub
author: Habib


navbar-links:
  Blog: "/"
  Projects: "projects"
  About Me / Contact: "aboutme"
  ❤ Support: "https://github.com/sponsors/habibhub"

avatar: "/assets/img/habib.jpeg"

social-network-links:
  email: "habiburhub@gmail.com"
  facebook: habibsuite
  github: habibhub
  twitter: arlinakiky
  
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: false

keywords: "habibur, habib, habibur rahaman, rahaman,"

link-col: "#404040"

mobile-theme-col: "#0085A1"

site-css: "/assets/css/custom-styles.css"
site-js: "/assets/js/custom-script.js"

edit_page_button: true

timezone: "India/Kolkata"
permalink: /blog/:title/
paginate: 10
paginate_path: "/page:num/"

disqus: "habib-hub"
# gtag: ""
# fb_app_id: ""

url-pretty: "❤ Support"
url-canonical: https://github.com/sponsors/habibhub

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      carbonads: true
      comments: true
      social-share: true
      show-share: true
      show-subscribe: true
      support_promo_box: true
      after-content: [share-section.html, scroll-box.html]
  -
    scope:
      path: "notblog"
    values:
      layout: "post"
      carbonads: true
      comments: true
      social-share: true
      show-share: true
      show-subscribe: true
      support_promo_box: true
      after-content: [share-section.html, scroll-box.html]
  -
    scope:
      path: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      before-content: [support_promo_box.html, carbonads.html]
      footer-extra: footer-subscribe.html

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/
  - files/java/Scrabble/*

# 2fc73a3a967e97599c9763d05e564189d5
